### PR TITLE
Line folding in HTTP headers is deprecated as of RFC7230

### PR DESCRIPTION
**Pull request by BigBlueHat**
...who knew, right?!

This switches the `Link` headers to be one per line--which reads pretty well still.

@azaroth42 cool? :smile:

### CODE REVIEW

**Comment by azaroth42** [comment]
Do we know the effects on other clients that might overwrite the previous header instance, rather than add to it? We could instead make it clear that the line break in the example is just for display purposes, and all of the headers MUST be on a single line without CRLF ?

**Comment by BigBlueHat** [comment]
AFAIK, node, PHP, and Python (at least) all support proper multiple header values--`Set-Cookie` is often used this way, fwiw, and apparently `Cache-Control` too from time to time.

I'm not keen on the examples not being valid requests. I'd prefer we do the multiple `Link` headers as one per line (as in this PR) and then (if you think we need) add a note about it also being possible to do a single `Link` header line with the various values concatenated with `,`...but that runs into header value limits and really isn't what folks will do anyhow.

We could invite others into this question (if you want), but I think that one per-line will do the trick and it's also more legible...which is a nice add. :smile:

**Comment by tilgovi** [comment]
:+1: all serious HTTP parsers should support multiple values for header keys. We should definitely not use something deprecated in the hopes that it better accommodates bad software.

**Comment by azaroth42** [comment]
Cool, just wanted to ask in case there was some system that treated them like a dictionary and hence would end up losing data.

**Pull request merged**
