### PR TITLE
Model to web annotation json ld doc

### PR DESCRIPTION
**Pull request by BigBlueHat**
Begin work on the JSON-LD bits for #97

### CODE REVIEW

**Comment by azaroth42** [comment]
Propose to merge after discussion on 12/2, assuming no :-1:s on the split.

**Comment by BigBlueHat** [comment]
@azaroth42 we're good to merge this, yes?

**Comment by azaroth42** [comment]
Can we put as a replacement to model, given the naming decision to stick with -model and add -vocab ?

**Comment by BigBlueHat** [comment]
@azaroth42 rebased, migrated over f58cabe, and renamed to `web-annotation-model`--I wasn't keen on overwriting `model` at this point, but we can do that once the document split is complete and confirmed by the WG. Just didn't want to cause more disruption than necessary.

More to do, obviously, but this gets us heading the right direction. Merge it if you're happy (enough) with it.

**Pull request merged**
