### PR TITLE
Added media types' table to the draft

### PR DESCRIPTION
**Pull request by iherman**
- Added the tables to a separate appendix
- Added a relevant text into the conformance section
- Labelled all other appendices as informative

This would close issue #203

### CODE REVIEW

**Comment by iherman** [comment]
The removal of CONTRIBUTOR.md is a side effect of some mess I did with my local github client; it is irrelevant to this change.

**Comment by azaroth42** [comment]
@iherman Did you intend to remove contributing and license files?

**Comment by azaroth42** [comment]
If we merge, it will remove the CONTRIBUTING and LICENSE files though. I'll add them back into the branch and merge

**Comment by iherman** [comment]
> On 20 May 2016, at 09:21, Rob Sanderson notifications@github.com wrote:
> 
> @iherman https://github.com/iherman Did you intend to remove contributing and license files?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub https://github.com/w3c/web-annotation/pull/235#issuecomment-220535686

See my comment. I will check again after this PR is done; I believe I had to change this and let me check that later.

I.

---

Ivan Herman, W3C 
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Ok. (I think the mess comes from the fact that some tool somewhere was messed up with capitalization of the file names:-(

**Pull request merged**
