### PR TITLE
Delete extraneous / unused content

### PR DESCRIPTION
**Pull request by azaroth42**
Tidy up in preparation for CR

### CODE REVIEW

**Comment by BigBlueHat** [comment]
:+1:

/cc @iherman @paolociccarese

**Comment by BigBlueHat** [comment]
I will note that I wish we had an "attic" (besides version history) for some of this content...but I also don't want it confusing people about what are doing, might do, etc. Just thinking...

**Comment by iherman** [comment]
Guys, I am not an editor, so I don't think I should be the one accepting this PR; the number of changes is so high that I can't judge it. It looks like an editorial change, on which we should trust you.

**Comment by iherman** [comment]
After short discussion with @azaroth42 it turns out that these are old stuffs that have, partially, been moved elsewhere. Accepting the PR.

**Pull request merged**
