### PR TITLE
Updating vocabulary

### PR DESCRIPTION
**Pull request by stain**
A quick take at #66 by going through http://w3c.github.io/web-annotation/model/wd2/ -- I didn't finish, but got to about section 4.2.

I want to add more of the external properties as well including isDefinedBy links,

Builds on pull request #187

### CODE REVIEW

**Comment by stain** [comment]
Pretty much complete now, deprecated all the old stuff. Not gone through the selectors yet.

Now I discovered http://w3c.github.io/web-annotation/vocab/wd/ which this is not in sync with - I don't know where is the ontology that http://w3c.github.io/web-annotation/vocab/wd/ is made from.

**Comment by iherman** [comment]
@azaroth42 @stain : I am not sure where we are with this pull request. The wd2 documents are now ready to be published on /TR, so any change would have to be included in the next release. But it would be good to have an updated version of the vocabulary and context files... where are we on those?

**Comment by azaroth42** [comment]
vocab/ is hand built, but the description of the ontology and the first part of the vocab document should be in sync (which is to say that's the desired state, and I don't know what the current state is)

**Comment by iherman** [comment]
If you feel things are fine as they are, then this should be closed without merge...

**Comment by stain** [comment]
I think you would want the updated oa.ttl, but not the generated oa.html.

How should we sort the folders? Shall I move oa.ttl to vocab/wd?

**Comment by iherman** [comment]
> On 29 Mar 2016, at 14:41, Stian Soiland-Reyes notifications@github.com wrote:
> 
> I think you would want the updated oa.ttl, but not the generated oa.html.
> 
> How should we sort the folders? Shall I move oa.ttl to vocab/wd?
> On 28 Mar 2016 17:03, "Ivan Herman" notifications@github.com wrote:

I woud leave this between you and @azaroth42. Just tell me what is where and I will push it to /ns...

**Comment by stain** [comment]
Now moved `vocabulary/oa.ttl` to `vocab/wd/oa.ttl` and changed the Makefile to write the .rdf and .jsonld variants to tmp/ (including license file header) 

-- do we need other formats for content negotiation on /ns/ ?

**Comment by stain** [comment]
@azaroth42 and @iherman - what is the difference between these files in vocab/wd ? 

```
-rw-rw-r-- 1 stain stain 290927 Mar 29 14:52 index.html
-rw-rw-r-- 1 stain stain  91253 Mar 29 14:52 index-linktemplate.html
-rw-rw-r-- 1 stain stain 106006 Mar 29 14:52 index-respec.html
```

I assume `index.html` is just the respec export from `index-respec.html` ? But then what is `index-linktemplate.html`?  Which one should I look at for updating `oa.ttl`?

**Comment by azaroth42** [comment]
Per the recently updated README (sorry for the confusion)... the linktemplate is the input that generates index-respec by running the python scripts.  The rationale for this was that there's a bunch of things that made life hell in OA days when we moved sections around, like numbering of examples and setting up links between sections.

**Comment by stain** [comment]
OK, this pull request is now complete for `oa.ttl`, `oa.rdf` and `oa.jsonld`  and is in sync with the published http://www.w3.org/TR/2016/WD-annotation-vocab-20160331/

Could someone else read through to see if it makes sense before publishing to http://www.w3.org/ns/ ? 

Useful HTML rendering: http://essepuntato.it/lode/owlapi/https://rawgit.com/stain/web-annotation/updating/vocab/wd/oa.ttl

**Comment by BigBlueHat** [comment]
@stain I didn't see anything glaring, but I also didn't read it word-for-word. :smile: Excited to see these generated, though! Thanks!

**Comment by stain** [comment]
Thanks, @BigBlueHat!

I think I got some of the `owl:Restriction`s wrong, as I get some `Error7` class appearing.. so I'll fix those first.

**Comment by stain** [comment]
@iherman I think this is ready to be merged, tagged as `WD-annotation-vocab-20160331` in github (for the `owl:versionIRI`) and put onto http://www.w3.org/ns/

I suggest to add to http://www.w3.org/ns/:
- oa.ttl
- oa.rdf
- (oa.jsonld - you would have to edit this one to replace the existing @graph )
- oa.html  (Namespace document)
- oa_files  (feel free to rename - but change it in `oa.html` -- you might want to replace/remove the existing https://www.w3.org/ns/LODEoa/ )

Feel free to edit oa.html - it's hand-edited from the result of tmp/oa.html to include RDFa

**Comment by stain** [comment]
the `vocab/wd/oa.jsonld`  of this pull request now includes the current `@context` from `jsonld/anno.jsonld`

I used http://json-ld.org/playground/ with compaction to combine the generated oa.jsonld with the vocabulary with the content of `jsonld/anno.jsonld` as the new context

**Comment by iherman** [comment]
@stain @azaroth42 @paolociccarese @BigBlueHat : I do not think I am in position of accepting this pull request myself. The PR modifies the Makefile for the generation of all the files, including the files Rob, Paolo, and Benjamin are editors of, and I cannot judge whether everything is fine or not. It may be all right, but this is not my call.

Looking at the changes, I have also two comments/questions:
- I may be a github issue, but the PR lists a large number of changes which include some changes that have been done elsewhere already on the core specification files (eg, my re-write of the status section comment on document splitting). It is _probably_ all right and it is just somehow incorporating earlier changes, but it looks strange to be listed there. Should we simply trust github?
- It seems that the right expression have been added to examples in the vocab document (or did I misread the diff file?).  But is it only done on some selected places? It is not clear to me. I think we should avoid not adding too complex things to examples overall.
- Does the pull request include adding binary/java files to the repo? The makefile seems to make use of specific java programs. Are we allowed to make such copies and put them to a repo without any further ado?

I am o.k. with the other changes overall but, again, I do not think it is my role to accept (or not) this PR.

**Comment by stain** [comment]
Agree that the editors should review.

I can squash the commits if you like - but still this would add several files - mainly because it moves `vocabulary/wd` to `vocab/wd`.
1. This adds a `Makefile` that also generates `index-respec.html` from `index-linktemplate.html` using `python make_links.py` as I understood from Rob is how it was done. Now I've undone the result of running that to simplify this pull request - so index*html no longer reflect your changes (See also #199 comments) and match `gh-pages` (e.g. they are just as much out of sync as on gh-pages :))
2. With "right expression" I am not sure what you mean.. I didn't include any examples in `owl.ttl` - but I did include `owl:Restrictions` for required properties. For "Suggested properties" I used `rdfs:seeAlso` -- although this could also in theory be done as "restrictions" with `owl:minQualifiedCardinality 0` ( @paolociccarese would know that style)
3. No binary or Java files are added to the repo. The Makefile downloads them from Apache and GitHub on the first run of `make`.  (But yes, their licenses are Apache License, so you could still add them to the repo if you really wanted)

**Comment by iherman** [comment]
> On 31 Mar 2016, at 11:04, Stian Soiland-Reyes notifications@github.com wrote:
> 
> Agree that the editors should review.
> 
> I can squash the commits if you like - but still this would add several files - mainly because it moves vocabulary/wd to vocab/wd.
> 
> This adds a Makefile that also generates index-respec.html from index-linktemplate.html using python make_links.py as I understood from Rob is how it was done. Now I've undone the result of running that to simplify this pull request - so index*html no longer reflect your changes (See also #199 https://github.com/w3c/web-annotation/issues/199 comments) and match gh-pages (e.g. they are just as much out of sync as on gh-pages :))
> With "right expression" I am not sure what you mean.. I didn't include any examples in owl.ttl - but I did include owl:Restrictions for required properties. For "Suggested properties" I used rdfs:seeAlso -- although this could also in theory be done as "restrictions" with owl:minQualifiedCardinality 0 ( @paolociccarese https://github.com/paolociccarese would know that style)

These changes are now gone with your latest move, they were in the index.html file. Question is moot:-)

> No binary or Java files are added to the repo. The Makefile downloads them from Apache and GitHub on the first run of make. (But yes, their licenses are Apache License, so you could still add them to the repo if you really wanted)
> Let us see for the future. To be honest, I do not think many people will run the makefile, so we can always amend this in future

Thanks!

**Pull request closed without merging**
