### PR TITLE
Updates for PR

### PR DESCRIPTION
**Pull request by azaroth42**
* Change status to PR
* Remove CR exit criteria (as already exited!)
* Remove reference to exit criteria
* Remove At Risk for AS2
* Remove redundant string body appendix

### CODE REVIEW

**Comment by iherman** [comment]
I would not have removed the exit criteria... yes, it is not really relevant, but it is part of the documents' history, just like the changes' section. Would it be possible to put them back?

**Comment by iherman** [comment]
As far as I can see, the changes' sections were not updated to record the changes between the latest CR and the PR

**Comment by azaroth42** [comment]
I looked at other Proposed Recs (eg dwbp) and they didn't have exit criteria, so I took them out.  I can put them back (just cut/paste), but I assume that for TR we'll take them out again, and compress the change history to only be differences with the CG's version?

There shouldn't be a reference to them in the status section though? Just the appendix?

**Comment by iherman** [comment]
> On 21 Dec 2016, at 19:10, Rob Sanderson <notifications@github.com> wrote:
> 
> I looked at other Proposed Recs (eg dwbp) and they didn't have exit criteria, so I took them out. I can put them back (just cut/paste), but I assume that for TR we'll take them out again, and compress the change history to only be differences with the CG's version?
> 
Actually, the PR and the Rec should not differ from one another except for spelling mistakes and the obvious status texts.

I would certainly keep the changes' section as is, and not compress it. It is part of the document's history. So is the CR exit criteria appendix.

I would propose to keep it that way. We can then ask Philippe & Ralph for advise on this; if they refer to take those out, then _I_ will do it before the PR publication, because I was the one asking for it. Is this a fair deal? ;-)

> There shouldn't be a reference to them in the status section though? Just the appendix?
> 

Indeed. I was only referring to the relevant appendix.

**Comment by azaroth42** [comment]
Deal :) My brief survey looking back through the announcements was 3 PRs without CR exit criteria, and one (webmention) with ... but webmention had it still in the Status ... so I think they're going to have to fix that for Rec!

Closing this and will re-edit rather than replace the text.

**Pull request closed without merging**
