### PR TITLE
Protocol Paging content editorial restructuring

### PR DESCRIPTION
**Pull request by BigBlueHat**
This reorganizing done by @azaroth42 has been super helpful to me (as an implementer) for understanding and clarifying the pagination structure of the Web Annotation Protocol.

I've reviewed these and am :+1: on incorporating them. However, I know the hour is late. :clock11: 

So. @iherman @tcole3 :thought_balloon:'s?

### CODE REVIEW

**Comment by iherman** [comment]
I assigned this to the V1 PR milestone, being more of an implementation feedback and editorial change.

If the CR publication of the vocabulary is delayed anyway, due to #313, we can reconsider and do this for the CR.

**Comment by BigBlueHat** [comment]
Here's a preview version with love from [RawGit](http://rawgit.com/):
https://rawgit.com/w3c/web-annotation/protocol-qs/protocol/wd/index.html

**Comment by iherman** [comment]
This way clearer than the previous version! Thanks

**Comment by iherman** [comment]
At the point where we are now, ie, the CR has not been published, I am fine incorporating these changes before we do a publication but only _after_ we close issue #313. Discussion on that issue may indeed lead to further changes even in these sections, so let us not create a mess...

**Comment by azaroth42** [comment]
Agreed. There's still some text to be written between some of the examples in the revised section, so it's not quite ready to go yet regardless.

**Comment by BigBlueHat** [comment]
@azaroth42 let me know how I can help with that text. Otherwise, I'm going to be testing against this version because hope is a thing with feathers. :bird:

**Comment by BigBlueHat** [comment]
Rebased on latest from master. Only conflicts were the publication date changes in the header in the generated `index.html`

**Comment by azaroth42** [comment]
Merging this and the other two PRs. We can sort out any issues later.

**Pull request merged**
