### PR TITLE
figures examples 39-44

### PR DESCRIPTION
**Pull request by pciccarese**

### CODE REVIEW

**Comment by azaroth42** [comment]
... pull requests can't be merged from a phone ... no idea what's up with that. Will merge at home, but it at least doesn't have conflicts :)

**Comment by iherman** [comment]
@azaroth42 there is now an extra check on PR-s done by W3C to make it sure that the PR is done by an 'authorized' user. This is done for IPR reasons (sigh...). Paolo was not yet in the system; I have added him and now all checks have passed.

I will merge the PR, to move on...

**Comment by paolociccarese** [comment]
@iherman thank you, I have two accounts on GH and I've used the alternative one for that commit.

**Comment by iherman** [comment]
I that's why! I was actually wondering why this didn't come up before, but I must admit I was too lazy to investigate further...

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by azaroth42** [comment]
Exported the images and updated the HTML, now at:
http://w3c.github.io/web-annotation/vocab/wd/

We're getting there :)

On Sun, Jun 5, 2016 at 7:38 AM, Ivan Herman notifications@github.com
wrote:

> I that's why! I was actually wondering why this didn't come up before, but
> I must admit I was too lazy to investigate further...
> 
> Ivan
> 
> ---
> 
> Ivan Herman
> Tel:+31 641044153
> http://www.ivan-herman.net
> 
> (Written on mobile, sorry for brevity and misspellings...)
> 
> > On 5 Jun 2016, at 15:36, Paolo Ciccarese notifications@github.com
> > wrote:
> > 
> > @iherman thank you, I have two accounts on GH and I've used the
> > alternative one for that commit.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/web-annotation/pull/268#issuecomment-223816707,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA1NvHn0ekatzTnJPlaEaXqBA7vXDLRBks5qIt9xgaJpZM4IuPmv
> .

## 

Rob Sanderson
Semantic Architect
The Getty Trust
Los Angeles, CA 90049

**Comment by paolociccarese** [comment]
@iherman actually it seems that also my other GitHub username 'paolociccarese' is not authorized. I apologize for that, I have two accounts on two different machines for work reasons :/

**Comment by iherman** [comment]
> On 6 Jun 2016, at 01:33, Paolo Ciccarese notifications@github.com wrote:
> 
> @iherman https://github.com/iherman actually it seems that also my other GitHub username 'paolociccarese' is not authorized. I apologize for that, I have two accounts on two different machines for work reasons :/
> 
> —

You should be o.k. now. We will see next time you do a PR whether the system check accepts it:-)

**Pull request merged**
