### PR TITLE
Fix example 15 in protocol

### PR DESCRIPTION
**Pull request by BigBlueHat**
@azaroth42 the Link headers in the post-Annotation-creation response were from the Container. I've updated them to match the prose that precedes the example.

Cheers!
:tophat:

### CODE REVIEW

**Comment by azaroth42** [comment]
The subject of the "triples" in the Link Headers is the requested URI, rather than the resource in the entity body.  Check example 11/12 in LDP: https://www.w3.org/TR/ldp/#ldpc-informative

So I believe that the current text is correct, just unintuitive.

**Comment by BigBlueHat** [comment]
Yeah... agree after reading RFC 5988 again also (see comment on #312).

Closing.

**Comment by BigBlueHat** [comment]
Hold up...reopening because the prose in that section is wrong if what you say (and the example) is correct.

Here's the prose from 5.1.

> The response MUST include a Link header with the target IRI of http://www.w3.org/ns/ldp#Resource and the rel parameter value of type to advertise that this is an RDF Source, according to the LDP specification [ldp]. It MAY also include the IRI http://www.w3.org/ns/oa#Annotation with the same rel parameter of type to also assert that it is an Annotation following the Web Annotation specifications.

So one of these things is incorrect (either the example or the prose)...right?

**Comment by BigBlueHat** [comment]
Closing via #315

**Pull request closed without merging**
